<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>12</LangVersion>
    <OutputPath>Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony">
      <Version>2.3.6</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="RimWorld.MultiplayerAPI">
      <Version>0.6.0</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Krafs.Rimworld.Ref">
      <Version>1.6.*</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Krafs.Publicizer">
      <Version>2.3.*</Version>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <Reference Include="Multiplayer_Compat">
      <HintPath>References\Multiplayer_Compat.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

	<ItemGroup>
		<Publicize Include="Assembly-CSharp;0Harmony" />
	</ItemGroup>

  <!-- Блок автокопирования в папку игры при сборке -->
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <PropertyGroup>
      <RimWorldModsPath>C:\Steam\steamapps\common\RimWorld\Mods\AstroMultiplayerCompability</RimWorldModsPath>
    </PropertyGroup>
    <Message Text="[Astro Build] Копирование файлов мода в RimWorld..." Importance="high" />
    <Copy SourceFiles="Assemblies\AstroMultiplayerCompability.dll" DestinationFolder="$(RimWorldModsPath)\Assemblies" />
    <ItemGroup>
      <AboutFiles Include="About\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(AboutFiles)" DestinationFiles="@(AboutFiles->'$(RimWorldModsPath)\About\%(RecursiveDir)%(Filename)%(Extension)')" />
    <Message Text="[Astro Build] Мод успешно скопирован в игру!" Importance="high" />
  </Target>

</Project>
